config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
# frozen_string_literal: true

class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, scope: [:cocktail_id]
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# frozen_string_literal: true

class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'cocktail was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
# frozen_string_literal: true

class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktails_path, notice: 'dose was successfully created.'
    else
      render :new
    end
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cocktails_helper.rb
# frozen_string_literal: true

module CocktailsHelper
end

app/helpers/doses_helper.rb
# frozen_string_literal: true

module DosesHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <%= f.input :photo, as: :file %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success", id: "submit" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>
<%= link_to 'Destroy', @cocktail, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/cocktails/index.html.erb
<!-- <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1486428263684-28ec9e4f2584?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2734&q=80)">
<h1>Behind The Bar</h1>
</div> -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1486428263684-28ec9e4f2584?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2734&q=80);">
  <div class="container">
    <h1>Behind The Bar</h1>
    <p>View and Create cocktail recipes from other mixologists like you!</p>
    <%= link_to 'Create a New Cocktail', new_cocktail_path, class: "btn btn-flat", id: "create" %>
  </div>
</div>

<%#= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
      width: 400, height: 300, crop: :fill) %>




<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h3 class="text-center">All Cocktails</h3>
      <ul>
        <% @cocktails.each do |cocktail| %>
        <li>
          <% if cocktail.photo.attached? %>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
              <div class="card-category py-3">
                <span class="cocktail-name"><%= cocktail.name%></span>
              </div>
              <div class="d-flex justify-content-end">
                <%= link_to 'Show More', cocktail, class: "btn btn-primary" %>
                <%= link_to 'Delete', cocktail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
              </div>
            </div>
            <% else  %>
              <div class="card" style="background-image: url('https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2786&q=80')">
                <div class="card-category py-3">
                  <span class="cocktail-name"><%= cocktail.name%></span>
                </div>
                <div class="d-flex justify-content-end">
                  <%= link_to 'Show More', cocktail, class: "btn btn-primary" %>
                  <%= link_to 'Delete', cocktail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                </div>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="add_cocktail">
  <div class="container">

    <h1>New Cocktail</h1>

    <%= render 'form', cocktail: @cocktail %>

    <%= link_to 'Back', cocktails_path, class: "btn btn-danger mt-1" %>

  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <% if @cocktail.photo.attached? %>
    <div class="card-category" style="background-image: url('<%= cl_image_path @cocktail.photo.key, height: 600, width: 400, crop: :fill
     %>')">
        <div class="container">
          <strong>Name:</strong>
          <h1><%= @cocktail.name %></h1>
          <ul><% @cocktail.doses.each do |dose| %>
            <li><%= dose.description %> - <%= dose.ingredient.name %></li>
          <% end %>
          </ul>
          <%= link_to 'Destroy', @cocktail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <%= link_to 'Edit', edit_cocktail_path(@cocktail), class: "btn btn-warning" %>
          <%= link_to 'View All Cocktails', cocktails_path, class: "btn btn-secondary" %>
          <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>
        </div>
    </div>
  <% else %>
    <div class="card-category" style="background-image: url('https://images.unsplash.com/photo-1536935338788-846bb9981813?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2786&q=80')">
        <div class="container">
          <strong>Name:</strong>
          <h1><%= @cocktail.name %></h1>
          <ul><% @cocktail.doses.each do |dose| %>
            <li><%= dose.description %> - <%= dose.ingredient.name %></li>
          <% end %>
          </ul>
          <%= link_to 'Destroy', @cocktail, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          <%= link_to 'Edit', edit_cocktail_path(@cocktail), class: "btn btn-warning" %>
          <%= link_to 'View All Cocktails', cocktails_path, class: "btn btn-secondary" %>
          <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail), class: "btn btn-success" %>
        </div>
    </div>
  <% end %>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :ingredient %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary w-100' %>
  </div>
<% end %>

app/views/doses/new.html.erb
<div class="add_dose">
  <div class="container">
    <h1>Create a new dose</h1>

    <%= render 'form', dose: @dose %>

    <%= link_to 'Back', cocktails_path %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Behind The Bar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>